name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install Cypress
      run: npm install cypress

    - name: Run Cypress Problem User
      run: npx cypress run --spec 'cypress/e2e/apiTest.cy.js'

    - name: Run Cypress Standard User Test
      run: npx cypress run --spec 'cypress/e2e/standarduser.cy.js'

    - name: Run Cypress Performance Glitch User
      run: npx cypress run --spec 'cypress/e2e/performance_glitch_user.cy.js'

    - name: Run Cypress Problem User
      run: npx cypress run --spec 'cypress/e2e/problem_user.cy.js'
